
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package edu.compscript.model.analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POW = 14;
  public static final int MULT = 12;
  public static final int CONST = 38;
  public static final int CHAR = 36;
  public static final int ENTERO = 3;
  public static final int DIFERENTE = 24;
  public static final int DOUBLE = 34;
  public static final int DOS_PUNTOS = 39;
  public static final int INT = 33;
  public static final int FOR = 41;
  public static final int LLAVE_IZQ = 46;
  public static final int NOT = 22;
  public static final int AND = 21;
  public static final int CARACTER = 6;
  public static final int IGUALDAD = 23;
  public static final int OR = 20;
  public static final int DIV = 13;
  public static final int INCREMENTO = 8;
  public static final int IF = 44;
  public static final int UMENOS = 19;
  public static final int ID = 5;
  public static final int EOF = 0;
  public static final int DECIMAL = 4;
  public static final int PARENT_IZQ = 17;
  public static final int TRUE = 42;
  public static final int DECREMENTO = 9;
  public static final int error = 1;
  public static final int FIN_CADENA = 7;
  public static final int CADENA = 2;
  public static final int MENOS = 11;
  public static final int MENOR = 25;
  public static final int MOD = 16;
  public static final int ASIGNACION = 40;
  public static final int MAYOR = 27;
  public static final int LOG = 31;
  public static final int ELSE = 45;
  public static final int LLAVE_DER = 47;
  public static final int PUNTO = 30;
  public static final int MAYOR_IGUAL = 28;
  public static final int LET = 37;
  public static final int BOOLEANO = 35;
  public static final int ROOT = 15;
  public static final int STRING = 32;
  public static final int MENOR_IGUAL = 26;
  public static final int FALSE = 43;
  public static final int PARENT_DER = 18;
  public static final int CONSOLE = 29;
  public static final int MAS = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "ID",
  "CARACTER",
  "FIN_CADENA",
  "INCREMENTO",
  "DECREMENTO",
  "MAS",
  "MENOS",
  "MULT",
  "DIV",
  "POW",
  "ROOT",
  "MOD",
  "PARENT_IZQ",
  "PARENT_DER",
  "UMENOS",
  "OR",
  "AND",
  "NOT",
  "IGUALDAD",
  "DIFERENTE",
  "MENOR",
  "MENOR_IGUAL",
  "MAYOR",
  "MAYOR_IGUAL",
  "CONSOLE",
  "PUNTO",
  "LOG",
  "STRING",
  "INT",
  "DOUBLE",
  "BOOLEANO",
  "CHAR",
  "LET",
  "CONST",
  "DOS_PUNTOS",
  "ASIGNACION",
  "FOR",
  "TRUE",
  "FALSE",
  "IF",
  "ELSE",
  "LLAVE_IZQ",
  "LLAVE_DER"
  };
}

